# Generated by Django 5.0.4 on 2024-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='other_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
